DROP DATABASE IF EXISTS swim_workoutsDB;
CREATE DATABASE swim_workoutsDB;
USE swim_workoutsDB;
CREATE TABLE workouts (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  distance INT NOT NULL,
  category VARCHAR(30) NOT NULL,
  wu TEXT (10000) NOT NULL,
  ms TEXT (10000) NOT NULL,
  cd TEXT (10000) NOT NULL
);