DROP DATABASE IF EXISTS swim_workoutsDB;
CREATE DATABASE swim_workoutsDB;
USE swim_workoutsDB;
CREATE TABLE workouts (
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  distance INT NOT NULL,
  category VARCHAR(30) NOT NULL,
  wu VARCHAR (45) NOT NULL,
  ms VARCHAR (10000) NOT NULL,
  cd VARCHAR (45) NOT NULL 
)